import oracledb
import sys
import os
from datetime import datetime, date, timedelta

# Enable thick mode for better compatibility with older Oracle database versions
# This must be called BEFORE any connection attempts
INSTANT_CLIENT_PATH = r"C:\instantclient_23_0"
THICK_MODE_ENABLED = False

# Try to initialize thick mode if Instant Client is available
if os.path.exists(INSTANT_CLIENT_PATH):
    try:
        oracledb.init_oracle_client(lib_dir=INSTANT_CLIENT_PATH)
        THICK_MODE_ENABLED = True
        print(f"✓ Oracle Instant Client initialized from {INSTANT_CLIENT_PATH}")
    except Exception as e:
        print(f"✗ Failed to initialize Oracle Instant Client: {e}")
        print("  The client library may be missing or damaged.")
else:
    print(f"✗ Oracle Instant Client not found at {INSTANT_CLIENT_PATH}")
    print("  Download from: https://www.oracle.com/database/technologies/instant-client/downloads.html")
    print("  Extract to C:\\instantclient_23_0 and restart the application")
    print()
    print("  Attempting connection in thin mode (may fail with older Oracle versions)...")

# Helper function to convert Oracle rows to dictionaries
def row_to_dict(cursor, row):
    """Convert a database row to a dictionary using cursor.description"""
    if row is None:
        return None
    columns = [col[0].lower() for col in cursor.description]
    return dict(zip(columns, row))

def get_connection():
    try:
        # Using thick mode connection with proper parameters
        try:
            # First try with explicit parameters (most compatible)
            connection = oracledb.connect(
                user="dbproject",
                password="123",
                host="localhost",
                port=1521,
                service_name="XE"
            )
            return connection
        except oracledb.Error:
            # Try with DSN format as fallback
            dsn = oracledb.makedsn("localhost", 1521, service_name="XE")
            connection = oracledb.connect(
                user="dbproject",
                password="123",
                dsn=dsn
            )
            return connection
    except Exception as e:
        print(f"Error connecting to Oracle DB: {e}")
        return None

def test_connection():
    """Test the database connection"""
    conn = get_connection()
    if not conn:
        print("✗ FATAL: Cannot connect to Oracle Database")
        print("  Make sure:")
        print("  1. Oracle Database is running")
        print("  2. Credentials are correct (user: dbproject, password: 123)")
        print("  3. Database is accessible at localhost:1521 with service name XE")
        return False
    
    try:
        cursor = conn.cursor()
        cursor.execute("SELECT 1 FROM DUAL")
        cursor.close()
        conn.close()
        print("✓ Database connection successful")
        return True
    except Exception as e:
        print(f"✗ Database connection test failed: {e}")
        try:
            conn.close()
        except:
            pass
        return False

def init_db():
    conn = get_connection()
    if not conn:
        print("Could not initialize DB connection.")
        return
    
    cursor = None
    try:
        cursor = conn.cursor()
        
        # Check if admin_users table exists
        cursor.execute("""
            SELECT count(*) FROM user_tables WHERE table_name = 'ADMIN_USERS'
        """)
        if cursor.fetchone()[0] == 0:
            print("Creating admin_users table...")
            cursor.execute("""
                CREATE TABLE admin_users (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR2(50) UNIQUE NOT NULL,
                    password_hash VARCHAR2(100) NOT NULL
                )
            """)
            # Insert default admin
            cursor.execute("""
                INSERT INTO admin_users (username, password_hash) VALUES ('admin', 'admin')
            """)
            conn.commit()

        # Check if complaint table exists
        cursor.execute("""
            SELECT count(*) FROM user_tables WHERE table_name = 'COMPLAINT'
        """)
        if cursor.fetchone()[0] == 0:
            print("Creating complaint table...")
            cursor.execute("""
                CREATE TABLE complaint (
                    complaint_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    customer_id NUMBER(10) NOT NULL,
                    complaint_date DATE DEFAULT SYSDATE NOT NULL,
                    description VARCHAR2(500) NOT NULL,
                    status VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
                    resolution VARCHAR2(500),
                    CONSTRAINT fk_comp_customer FOREIGN KEY (customer_id) REFERENCES customer(customer_id)
                )
            """)
            conn.commit()
    except oracledb.Error as e:
        print(f"Error initializing DB: {e}")
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

def get_dashboard_stats():
    conn = get_connection()
    if not conn:
        return {"total_customers": 0, "total_bills": 0, "pending_bills": 0, "complaints_count": 0}

    cursor = None
    try:
        stats = {}
        cursor = conn.cursor()

        cursor.execute("SELECT COUNT(*) FROM customer")
        stats['total_customers'] = cursor.fetchone()[0]

        cursor.execute("SELECT COUNT(*) FROM invoice")
        stats['total_bills'] = cursor.fetchone()[0]

        cursor.execute("SELECT COUNT(*) FROM invoice WHERE invoice_status = 'UNPAID'")
        stats['pending_bills'] = cursor.fetchone()[0]

        cursor.execute("SELECT COUNT(*) FROM complaint WHERE status = 'OPEN'")
        stats['complaints_count'] = cursor.fetchone()[0]

        return stats
    except oracledb.Error as e:
        print(f"Error getting dashboard stats: {e}")
        return {"total_customers": 0, "total_bills": 0, "pending_bills": 0, "complaints_count": 0}
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

# --- Customer CRUD ---
def get_all_customers():
    conn = get_connection()
    if not conn:
        return []

    cursor = None
    try:
        cursor = conn.cursor()
        # Include active subscription plan name (if any).
        # Prefer the operational view if it exists; otherwise fall back to direct joins.
        query_candidates = [
            """
            SELECT c.customer_id,
                   c.first_name,
                   c.last_name,
                   c.cnic,
                   c.phone_number,
                   c.customer_type,
                   c.account_status,
                   vas.plan_name AS plan_name
            FROM customer c
            LEFT JOIN vw_active_subscriptions vas
                ON vas.customer_id = c.customer_id
            ORDER BY c.customer_id DESC
            """,
            """
            SELECT c.customer_id,
                   c.first_name,
                   c.last_name,
                   c.cnic,
                   c.phone_number,
                   c.customer_type,
                   c.account_status,
                   sp.plan_name AS plan_name
            FROM customer c
            LEFT JOIN customer_subscription cs
                ON cs.customer_id = c.customer_id
               AND cs.subscription_status = 'ACTIVE'
               AND (cs.end_date IS NULL OR cs.end_date > SYSDATE)
            LEFT JOIN subscription_plan sp
                ON sp.plan_id = cs.plan_id
            ORDER BY c.customer_id DESC
            """,
            """
            SELECT customer_id,
                   first_name,
                   last_name,
                   cnic,
                   phone_number,
                   customer_type,
                   account_status,
                   CAST(NULL AS VARCHAR2(100)) AS plan_name
            FROM customer
            ORDER BY customer_id DESC
            """,
        ]

        customers = []
        last_err = None
        for q in query_candidates:
            try:
                cursor.execute(q)
                customers = [row_to_dict(cursor, row) for row in cursor.fetchall()]
                last_err = None
                break
            except Exception as e:
                last_err = e
                continue

        if last_err:
            print(f"Warning: failed to load customers with plan info: {last_err}")
        return [c for c in customers if c is not None]
    except oracledb.Error as e:
        print(f"Error getting customers: {e}")
        return []
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

def get_customer_by_id(customer_id):
    conn = get_connection()
    if not conn:
        return None

    cursor = None
    try:
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM customer WHERE customer_id = :1", (customer_id,))
        row = cursor.fetchone()
        customer = row_to_dict(cursor, row)
        return customer
    except oracledb.Error as e:
        print(f"Error getting customer {customer_id}: {e}")
        return None
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

def add_customer(data):
    conn = get_connection()
    if not conn:
        return False, "Database connection failed"

    cursor = None
    try:
        cursor = conn.cursor()
        cursor.execute("SELECT NVL(MAX(customer_id), 0) + 1 FROM customer")
        new_id = cursor.fetchone()[0]

        cursor.execute("""
            INSERT INTO customer (
                customer_id, cnic, first_name, last_name, date_of_birth,
                gender, phone_number, email, city, address, customer_type, account_status
            ) VALUES (
                :1, :2, :3, :4, TO_DATE(:5, 'YYYY-MM-DD'), :6, :7, :8, :9, :10, :11, 'ACTIVE'
            )
        """, (
            new_id, data['cnic'], data['first_name'], data['last_name'],
            data['date_of_birth'], data['gender'], data['phone_number'],
            data['email'], data['city'], data['address'], data['customer_type']
        ))
        conn.commit()
        return True, "Customer added successfully."
    except oracledb.Error as e:
        if conn:
            conn.rollback()
        return False, str(e)
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

def delete_customer(customer_id):
    conn = get_connection()
    if not conn:
        return False, "Database connection failed"

    cursor = None
    try:
        cursor = conn.cursor()
        cursor.execute("DELETE FROM customer WHERE customer_id = :1", (customer_id,))
        conn.commit()
        return True, "Customer deleted successfully."
    except oracledb.Error as e:
        if conn:
            conn.rollback()
        return False, str(e)
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

# --- Billing (Invoices) CRUD ---
def get_all_invoices():
    conn = get_connection()
    if not conn:
        return []

    cursor = None
    try:
        cursor = conn.cursor()
        # Try to include subscription plan info (table/column names may differ across schemas).
        query_candidates = [
            # Project schema: customer_subscription + subscription_plan (active subscription)
            """
            SELECT i.invoice_id,
                   c.first_name || ' ' || c.last_name as customer_name,
                   sp.plan_name as plan_name,
                   i.total_amount, i.due_date, i.invoice_status
            FROM invoice i
            JOIN customer c ON i.customer_id = c.customer_id
            LEFT JOIN customer_subscription cs
                ON cs.customer_id = c.customer_id
               AND cs.subscription_status = 'ACTIVE'
               AND (cs.end_date IS NULL OR cs.end_date > SYSDATE)
            LEFT JOIN subscription_plan sp
                ON sp.plan_id = cs.plan_id
            ORDER BY i.due_date DESC
            """,
            # View-based (if created)
            """
            SELECT i.invoice_id,
                   c.first_name || ' ' || c.last_name as customer_name,
                   vas.plan_name as plan_name,
                   i.total_amount, i.due_date, i.invoice_status
            FROM invoice i
            JOIN customer c ON i.customer_id = c.customer_id
            LEFT JOIN vw_active_subscriptions vas
                ON vas.customer_id = c.customer_id
            ORDER BY i.due_date DESC
            """,
            # Fallback (no plan info)
            """
            SELECT i.invoice_id,
                   c.first_name || ' ' || c.last_name as customer_name,
                   CAST(NULL AS VARCHAR2(100)) as plan_name,
                   i.total_amount, i.due_date, i.invoice_status
            FROM invoice i
            JOIN customer c ON i.customer_id = c.customer_id
            ORDER BY i.due_date DESC
            """,
        ]

        invoices = []
        last_err = None
        for q in query_candidates:
            try:
                cursor.execute(q)
                invoices = [row_to_dict(cursor, row) for row in cursor.fetchall()]
                last_err = None
                break
            except Exception as e:
                last_err = e
                continue
        if last_err:
            print(f"Warning: failed to load invoices with plan info: {last_err}")

        return [inv for inv in invoices if inv is not None]
    except oracledb.Error as e:
        print(f"Error getting invoices: {e}")
        return []
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

def get_customers_for_billing():
    """
    Return customers with best-effort plan/subscription label (if schema supports it).
    Used by billing UI so the operator can see which plan a customer is on.
    """
    conn = get_connection()
    if not conn:
        return []

    cursor = None
    try:
        cursor = conn.cursor()
        query_candidates = [
            # Project schema: customer_subscription + subscription_plan (active subscription)
            """
            SELECT c.customer_id,
                   c.first_name, c.last_name, c.cnic,
                   sp.plan_name as plan_name
            FROM customer c
            LEFT JOIN customer_subscription cs
                ON cs.customer_id = c.customer_id
               AND cs.subscription_status = 'ACTIVE'
               AND (cs.end_date IS NULL OR cs.end_date > SYSDATE)
            LEFT JOIN subscription_plan sp
                ON sp.plan_id = cs.plan_id
            ORDER BY c.customer_id DESC
            """,
            # View-based (if created)
            """
            SELECT c.customer_id,
                   c.first_name, c.last_name, c.cnic,
                   vas.plan_name as plan_name
            FROM customer c
            LEFT JOIN vw_active_subscriptions vas
                ON vas.customer_id = c.customer_id
            ORDER BY c.customer_id DESC
            """,
            """
            SELECT c.customer_id,
                   c.first_name, c.last_name, c.cnic,
                   CAST(NULL AS VARCHAR2(100)) as plan_name
            FROM customer c
            ORDER BY c.customer_id DESC
            """,
        ]
        customers = []
        last_err = None
        for q in query_candidates:
            try:
                cursor.execute(q)
                customers = [row_to_dict(cursor, row) for row in cursor.fetchall()]
                last_err = None
                break
            except Exception as e:
                last_err = e
                continue
        if last_err:
            print(f"Warning: failed to load customers with plan info: {last_err}")
        return [c for c in customers if c is not None]
    except Exception as e:
        print(f"Error getting customers for billing: {e}")
        return []
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

def get_all_plans(active_only=True):
    """Return subscription plans (optionally only ACTIVE plans)."""
    conn = get_connection()
    if not conn:
        return []

    cursor = None
    try:
        cursor = conn.cursor()
        if active_only:
            cursor.execute("""
                SELECT plan_id, plan_name, plan_type, monthly_rental, validity_days, plan_status
                FROM subscription_plan
                WHERE plan_status = 'ACTIVE'
                ORDER BY plan_type, plan_name
            """)
        else:
            cursor.execute("""
                SELECT plan_id, plan_name, plan_type, monthly_rental, validity_days, plan_status
                FROM subscription_plan
                ORDER BY plan_type, plan_name
            """)
        plans = [row_to_dict(cursor, row) for row in cursor.fetchall()]
        return [p for p in plans if p is not None]
    except Exception as e:
        print(f"Error getting plans: {e}")
        return []
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

def get_active_subscriptions():
    """Return active subscriptions with customer and plan details."""
    conn = get_connection()
    if not conn:
        return []

    cursor = None
    try:
        cursor = conn.cursor()
        query_candidates = [
            """
            SELECT customer_id,
                   customer_name,
                   phone_number,
                   plan_id,
                   plan_name,
                   plan_type,
                   monthly_rental,
                   start_date,
                   end_date,
                   validity_days,
                   subscription_fee_paid
            FROM vw_active_subscriptions
            ORDER BY start_date DESC
            """,
            """
            SELECT cs.customer_id,
                   c.first_name || ' ' || c.last_name AS customer_name,
                   c.phone_number,
                   sp.plan_id,
                   sp.plan_name,
                   sp.plan_type,
                   sp.monthly_rental,
                   cs.start_date,
                   cs.end_date,
                   sp.validity_days,
                   cs.subscription_fee_paid
            FROM customer_subscription cs
            JOIN customer c ON cs.customer_id = c.customer_id
            JOIN subscription_plan sp ON sp.plan_id = cs.plan_id
            WHERE cs.subscription_status = 'ACTIVE'
              AND (cs.end_date IS NULL OR cs.end_date > SYSDATE)
            ORDER BY cs.start_date DESC
            """,
        ]

        subs = []
        last_err = None
        for q in query_candidates:
            try:
                cursor.execute(q)
                subs = [row_to_dict(cursor, row) for row in cursor.fetchall()]
                last_err = None
                break
            except Exception as e:
                last_err = e
                continue

        if last_err:
            print(f"Warning: failed to load active subscriptions: {last_err}")
        return [s for s in subs if s is not None]
    except Exception as e:
        print(f"Error getting active subscriptions: {e}")
        return []
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

def subscribe_customer_to_plan(customer_id, plan_id, start_date_s=None, subscription_fee_paid=None, generate_invoice=True):
    """
    Subscribe a customer to a plan and (optionally) auto-generate an invoice for the plan rental.

    Returns: (success: bool, message: str, invoice_id: int|None)
    """
    conn = get_connection()
    if not conn:
        return False, "Database connection failed", None

    cursor = None
    try:
        cursor = conn.cursor()

        # Parse start_date (default today)
        if start_date_s:
            start_dt = datetime.strptime(start_date_s, "%Y-%m-%d").date()
        else:
            start_dt = date.today()

        # Load plan details
        cursor.execute("""
            SELECT plan_name, monthly_rental, validity_days, plan_status
            FROM subscription_plan
            WHERE plan_id = :1
        """, (plan_id,))
        plan_row = cursor.fetchone()
        if not plan_row:
            return False, "Plan not found.", None

        plan_name, monthly_rental, validity_days, plan_status = plan_row
        if plan_status != "ACTIVE":
            return False, "Selected plan is not ACTIVE.", None

        validity_days = int(validity_days) if validity_days is not None else 30
        rental = float(monthly_rental) if monthly_rental is not None else 0.0

        # Compute end_date for this subscription (inclusive)
        end_dt = start_dt + timedelta(days=max(validity_days, 1) - 1)

        # Default fee paid = rental (common for prepaid plan purchase)
        if subscription_fee_paid is None or subscription_fee_paid == "":
            fee_paid = rental
        else:
            fee_paid = float(subscription_fee_paid)

        # Insert subscription
        cursor.execute("""
            INSERT INTO customer_subscription (
                customer_id, plan_id, start_date, end_date,
                subscription_status, subscription_fee_paid
            ) VALUES (
                :1, :2, TO_DATE(:3,'YYYY-MM-DD'), TO_DATE(:4,'YYYY-MM-DD'),
                'ACTIVE', :5
            )
        """, (customer_id, plan_id, start_dt.strftime("%Y-%m-%d"), end_dt.strftime("%Y-%m-%d"), fee_paid))

        new_invoice_id = None
        if generate_invoice:
            # Ensure due_date satisfies ck_invoice_due (due_date >= generated_date)
            gen_dt = date.today()
            anchor_dt = end_dt if end_dt > gen_dt else gen_dt
            due_dt = anchor_dt + timedelta(days=10)

            # Generate invoice
            cursor.execute("SELECT NVL(MAX(invoice_id), 0) + 1 FROM invoice")
            new_invoice_id = int(cursor.fetchone()[0])

            usage = 0.0
            tax = 0.0
            total = rental + usage + tax

            cursor.execute("""
                INSERT INTO invoice (
                    invoice_id, customer_id, billing_period_start, billing_period_end,
                    due_date, usage_charges, rental_charges, tax_amount, total_amount, invoice_status
                ) VALUES (
                    :1, :2, TO_DATE(:3,'YYYY-MM-DD'), TO_DATE(:4,'YYYY-MM-DD'),
                    TO_DATE(:5,'YYYY-MM-DD'), :6, :7, :8, :9, 'UNPAID'
                )
            """, (
                new_invoice_id, customer_id,
                start_dt.strftime("%Y-%m-%d"), end_dt.strftime("%Y-%m-%d"),
                due_dt.strftime("%Y-%m-%d"),
                usage, rental, tax, total
            ))

        conn.commit()
        if new_invoice_id:
            return True, f"Subscribed to '{plan_name}'. Invoice INV-{new_invoice_id:06d} generated.", new_invoice_id
        return True, f"Subscribed to '{plan_name}'.", None
    except Exception as e:
        try:
            conn.rollback()
        except Exception:
            pass
        return False, f"Subscription failed: {str(e)}", None
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

def generate_invoice(data):
    conn = get_connection()
    if not conn:
        return False, "Database connection failed"

    cursor = None
    try:
        cursor = conn.cursor()
        cursor.execute("SELECT NVL(MAX(invoice_id), 0) + 1 FROM invoice")
        new_id = cursor.fetchone()[0]
        cursor.execute("""
            INSERT INTO invoice (
                invoice_id, customer_id, billing_period_start, billing_period_end,
                due_date, usage_charges, rental_charges, tax_amount, total_amount, invoice_status
            ) VALUES (
                :1, :2, TO_DATE(:3, 'YYYY-MM-DD'), TO_DATE(:4, 'YYYY-MM-DD'),
                TO_DATE(:5, 'YYYY-MM-DD'), :6, :7, :8, :9, 'UNPAID'
            )
        """, (
            new_id, data['customer_id'], data['period_start'], data['period_end'],
            data['due_date'], data['usage_charges'], data['rental_charges'],
            data['tax_amount'], data['total_amount']
        ))
        conn.commit()
        return True, "Invoice generated successfully."
    except oracledb.Error as e:
        if conn:
            conn.rollback()
        return False, str(e)
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

def update_invoice_status(invoice_id, status):
    conn = get_connection()
    if not conn:
        return False, "Database connection failed"
        
    cursor = None
    try:
        cursor = conn.cursor()
        cursor.execute("UPDATE invoice SET invoice_status = :1 WHERE invoice_id = :2", (status, invoice_id))
        conn.commit()
        return True, "Invoice status updated."
    except oracledb.Error as e:
        if conn:
            conn.rollback()
        return False, str(e)
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

# --- Payments CRUD ---
def get_all_payments():
    conn = get_connection()
    if not conn:
        return []

    cursor = None
    try:
        cursor = conn.cursor()
        cursor.execute("""
            SELECT p.payment_id, p.invoice_id, p.payment_date, p.amount_paid, p.payment_method, p.payment_status
            FROM payment p
            ORDER BY p.payment_date DESC
        """)
        payments = [row_to_dict(cursor, row) for row in cursor.fetchall()]
        return [pmt for pmt in payments if pmt is not None]
    except oracledb.Error as e:
        print(f"Database error in get_all_payments: {e}")
        return []
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

def add_payment(data):
    conn = get_connection()
    if not conn:
        return False, "Database connection failed"

    cursor = None
    try:
        cursor = conn.cursor()
        cursor.execute("SELECT NVL(MAX(payment_id), 0) + 1 FROM payment")
        new_id = cursor.fetchone()[0]
        cursor.execute("""
            INSERT INTO payment (
                payment_id, invoice_id, amount_paid, payment_method, transaction_reference
            ) VALUES (
                :1, :2, :3, :4, :5
            )
        """, (
            new_id, data['invoice_id'], data['amount_paid'], data['payment_method'], data['transaction_reference']
        ))
        
        # Also update invoice amount_paid and status
        cursor.execute("""
            UPDATE invoice
            SET amount_paid = amount_paid + :1,
                invoice_status = CASE
                    WHEN total_amount <= (amount_paid + :1) THEN 'PAID'
                    ELSE 'PARTIAL'
                END
            WHERE invoice_id = :2
        """, (data['amount_paid'], data['amount_paid'], data['invoice_id']))
        conn.commit()
        return True, "Payment added successfully."
    except oracledb.Error as e:
        if conn:
            conn.rollback()
        return False, str(e)
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

# --- Complaints CRUD ---
def get_all_complaints():
    conn = get_connection()
    if not conn:
        return []

    cursor = None
    try:
        cursor = conn.cursor()
        cursor.execute("""
            SELECT c.complaint_id, c.customer_id, cu.first_name || ' ' || cu.last_name as customer_name,
                   c.submitted_date as complaint_date, c.description, c.status, c.resolution_notes as resolution,
                   c.complaint_type, c.priority
            FROM complaint c
            JOIN customer cu ON c.customer_id = cu.customer_id
            ORDER BY c.submitted_date DESC
        """)
        complaints = [row_to_dict(cursor, row) for row in cursor.fetchall()]
        return [cmp for cmp in complaints if cmp is not None]
    except oracledb.Error as e:
        print(f"Database error in get_all_complaints: {e}")
        return []
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

def add_complaint(data):
    conn = get_connection()
    if not conn:
        return False, "Database connection failed"
        
    cursor = None
    try:
        cursor = conn.cursor()
        
        # Generate new complaint_id
        cursor.execute("SELECT NVL(MAX(complaint_id), 0) + 1 FROM complaint")
        new_id = int(cursor.fetchone()[0])
        
        cursor.execute("""
            INSERT INTO complaint (complaint_id, customer_id, complaint_type, priority, description) 
            VALUES (:1, :2, :3, :4, :5)
        """, (new_id, data['customer_id'], data.get('complaint_type', 'OTHER'), data.get('priority', 'MEDIUM'), data['description']))
        conn.commit()
        return True, "Complaint submitted successfully."
    except oracledb.Error as e:
        if conn:
            conn.rollback()
        return False, str(e)
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

def resolve_complaint(complaint_id, resolution):
    conn = get_connection()
    if not conn:
        return False, "Database connection failed"
        
    cursor = None
    try:
        cursor = conn.cursor()
        cursor.execute("""
            UPDATE complaint 
            SET status = 'RESOLVED', resolution_notes = :1, resolved_date = SYSDATE
            WHERE complaint_id = :2
        """, (resolution, complaint_id))
        conn.commit()
        return True, "Complaint resolved successfully."
    except oracledb.Error as e:
        if conn:
            conn.rollback()
        return False, str(e)
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

def reject_complaint(complaint_id, reason):
    conn = get_connection()
    if not conn:
        return False, "Database connection failed"
        
    cursor = None
    try:
        cursor = conn.cursor()
        cursor.execute("""
            UPDATE complaint 
            SET status = 'REJECTED', resolution_notes = :1, resolved_date = SYSDATE
            WHERE complaint_id = :2
        """, (reason, complaint_id))
        conn.commit()
        return True, "Complaint rejected successfully."
    except oracledb.Error as e:
        if conn:
            conn.rollback()
        return False, str(e)
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

# --- Monthly Report ---
def get_monthly_report(year=None, month=None):
    """Generate a comprehensive monthly report summary"""
    from datetime import datetime
    
    if year is None:
        year = datetime.now().year
    if month is None:
        month = datetime.now().month
    
    # Initialize report with default values
    report = {
        'year': year,
        'month': month,
        'month_name': datetime(year, month, 1).strftime('%B %Y'),
        'total_active_customers': 0,
        'total_revenue': 0,
        'total_payments': 0,
        # Accounts receivable as-of-now (all unpaid/partial invoices)
        'outstanding_amount': 0,
        # Outstanding limited to invoices in the selected month
        'outstanding_amount_month': 0,
        'invoice_status_breakdown': {},
        'payment_methods': [],
        'open_complaints': 0,
        'top_customers': [],
        'new_customers': 0,
        'invoice_count_month': 0,
        'payments_count_month': 0,
        'avg_invoice_value_month': 0,
        'avg_payment_value_month': 0,
        # Collections/outstanding views that look professional in a report
        'outstanding_by_customer': [],
        'aging_buckets': {
            'current': 0,
            '1_30': 0,
            '31_60': 0,
            '61_90': 0,
            '90_plus': 0,
        },
    }
    
    try:
        # Total active customers
        try:
            conn = get_connection()
            if conn:
                cursor = conn.cursor()
                cursor.execute("SELECT COUNT(*) FROM customer WHERE account_status = 'ACTIVE'")
                row = cursor.fetchone()
                report['total_active_customers'] = row[0] if row else 0
                cursor.close()
                conn.close()
                print(f"✓ Active customers: {report['total_active_customers']}")
        except Exception as e:
            print(f"✗ Error getting active customers: {e}")
        
        # Total revenue (invoices) for the month using EXTRACT
        try:
            conn = get_connection()
            if conn:
                cursor = conn.cursor()
                cursor.execute("""
                    SELECT NVL(SUM(total_amount), 0) FROM invoice 
                    WHERE EXTRACT(YEAR FROM billing_period_start) = :1
                    AND EXTRACT(MONTH FROM billing_period_start) = :2
                """, (year, month))
                row = cursor.fetchone()
                report['total_revenue'] = float(row[0]) if row else 0
                cursor.close()
                conn.close()
                print(f"✓ Total revenue: {report['total_revenue']}")
        except Exception as e:
            print(f"✗ Error getting revenue: {e}")
        
        # Invoice count for the month
        try:
            conn = get_connection()
            if conn:
                cursor = conn.cursor()
                cursor.execute("""
                    SELECT COUNT(*) FROM invoice
                    WHERE EXTRACT(YEAR FROM billing_period_start) = :1
                    AND EXTRACT(MONTH FROM billing_period_start) = :2
                """, (year, month))
                row = cursor.fetchone()
                report['invoice_count_month'] = int(row[0]) if row else 0
                cursor.close()
                conn.close()
        except Exception as e:
            print(f"✗ Error getting invoice count: {e}")

        # Total payments received for the month
        try:
            conn = get_connection()
            if conn:
                cursor = conn.cursor()
                cursor.execute("""
                    SELECT NVL(SUM(amount_paid), 0) FROM payment 
                    WHERE EXTRACT(YEAR FROM payment_date) = :1
                    AND EXTRACT(MONTH FROM payment_date) = :2
                """, (year, month))
                row = cursor.fetchone()
                report['total_payments'] = float(row[0]) if row else 0
                cursor.close()
                conn.close()
                print(f"✓ Total payments: {report['total_payments']}")
        except Exception as e:
            print(f"✗ Error getting payments: {e}")

        # Payment count for the month
        try:
            conn = get_connection()
            if conn:
                cursor = conn.cursor()
                cursor.execute("""
                    SELECT COUNT(*) FROM payment
                    WHERE EXTRACT(YEAR FROM payment_date) = :1
                    AND EXTRACT(MONTH FROM payment_date) = :2
                """, (year, month))
                row = cursor.fetchone()
                report['payments_count_month'] = int(row[0]) if row else 0
                cursor.close()
                conn.close()
        except Exception as e:
            print(f"✗ Error getting payment count: {e}")
        
        # Outstanding amount (unpaid + partial)
        try:
            conn = get_connection()
            if conn:
                cursor = conn.cursor()
                cursor.execute("""
                    SELECT NVL(SUM(total_amount - NVL(amount_paid, 0)), 0) FROM invoice 
                    WHERE invoice_status IN ('UNPAID', 'PARTIAL')
                """)
                row = cursor.fetchone()
                report['outstanding_amount'] = float(row[0]) if row else 0
                cursor.close()
                conn.close()
                print(f"✓ Outstanding amount: {report['outstanding_amount']}")
        except Exception as e:
            print(f"✗ Error getting outstanding: {e}")

        # Outstanding amount limited to selected month invoices
        try:
            conn = get_connection()
            if conn:
                cursor = conn.cursor()
                cursor.execute("""
                    SELECT NVL(SUM(total_amount - NVL(amount_paid, 0)), 0) FROM invoice
                    WHERE invoice_status IN ('UNPAID', 'PARTIAL')
                    AND EXTRACT(YEAR FROM billing_period_start) = :1
                    AND EXTRACT(MONTH FROM billing_period_start) = :2
                """, (year, month))
                row = cursor.fetchone()
                report['outstanding_amount_month'] = float(row[0]) if row else 0
                cursor.close()
                conn.close()
        except Exception as e:
            print(f"✗ Error getting monthly outstanding: {e}")

        # Outstanding by customer (top 10) as-of-now
        try:
            conn = get_connection()
            if conn:
                cursor = conn.cursor()
                cursor.execute("""
                    SELECT
                        cu.customer_id,
                        cu.first_name || ' ' || cu.last_name AS name,
                        COUNT(i.invoice_id) AS invoice_count,
                        NVL(SUM(i.total_amount - NVL(i.amount_paid, 0)), 0) AS outstanding
                    FROM customer cu
                    JOIN invoice i ON i.customer_id = cu.customer_id
                    WHERE i.invoice_status IN ('UNPAID', 'PARTIAL')
                    GROUP BY cu.customer_id, cu.first_name, cu.last_name
                    ORDER BY outstanding DESC
                """)
                rows = cursor.fetchall()
                outstanding_by_customer = []
                for idx, row in enumerate(rows or []):
                    if not row or idx >= 10:
                        break
                    outstanding_by_customer.append({
                        'customer_id': row[0],
                        'name': row[1],
                        'invoice_count': int(row[2]) if row[2] is not None else 0,
                        'outstanding': float(row[3]) if row[3] is not None else 0,
                    })
                report['outstanding_by_customer'] = outstanding_by_customer
                cursor.close()
                conn.close()
        except Exception as e:
            print(f"✗ Error getting outstanding by customer: {e}")

        # Aging buckets for outstanding invoices as-of-now (based on due_date vs SYSDATE)
        try:
            conn = get_connection()
            if conn:
                cursor = conn.cursor()
                cursor.execute("""
                    SELECT
                        SUM(CASE WHEN TRUNC(SYSDATE) <= TRUNC(due_date)
                            THEN (total_amount - NVL(amount_paid, 0)) ELSE 0 END) AS current_amt,
                        SUM(CASE WHEN TRUNC(SYSDATE) > TRUNC(due_date) AND TRUNC(SYSDATE) - TRUNC(due_date) BETWEEN 1 AND 30
                            THEN (total_amount - NVL(amount_paid, 0)) ELSE 0 END) AS a_1_30,
                        SUM(CASE WHEN TRUNC(SYSDATE) - TRUNC(due_date) BETWEEN 31 AND 60
                            THEN (total_amount - NVL(amount_paid, 0)) ELSE 0 END) AS a_31_60,
                        SUM(CASE WHEN TRUNC(SYSDATE) - TRUNC(due_date) BETWEEN 61 AND 90
                            THEN (total_amount - NVL(amount_paid, 0)) ELSE 0 END) AS a_61_90,
                        SUM(CASE WHEN TRUNC(SYSDATE) - TRUNC(due_date) > 90
                            THEN (total_amount - NVL(amount_paid, 0)) ELSE 0 END) AS a_90_plus
                    FROM invoice
                    WHERE invoice_status IN ('UNPAID', 'PARTIAL')
                """)
                row = cursor.fetchone()
                if row:
                    report['aging_buckets'] = {
                        'current': float(row[0] or 0),
                        '1_30': float(row[1] or 0),
                        '31_60': float(row[2] or 0),
                        '61_90': float(row[3] or 0),
                        '90_plus': float(row[4] or 0),
                    }
                cursor.close()
                conn.close()
        except Exception as e:
            print(f"✗ Error getting aging buckets: {e}")
        
        # Invoice status breakdown
        try:
            conn = get_connection()
            if conn:
                cursor = conn.cursor()
                cursor.execute("""
                    SELECT invoice_status, COUNT(*) as count 
                    FROM invoice 
                    WHERE EXTRACT(YEAR FROM billing_period_start) = :1
                    AND EXTRACT(MONTH FROM billing_period_start) = :2
                    GROUP BY invoice_status
                """, (year, month))
                status_breakdown = {}
                rows = cursor.fetchall()
                for row in rows:
                    if row:
                        status_breakdown[row[0]] = row[1]
                report['invoice_status_breakdown'] = status_breakdown
                cursor.close()
                conn.close()
                print(f"✓ Invoice status breakdown: {status_breakdown}")
        except Exception as e:
            print(f"✗ Error getting invoice status breakdown: {e}")
        
        # Payment method breakdown
        try:
            conn = get_connection()
            if conn:
                cursor = conn.cursor()
                cursor.execute("""
                    SELECT payment_method, COUNT(*) as count, NVL(SUM(amount_paid), 0) as total
                    FROM payment 
                    WHERE EXTRACT(YEAR FROM payment_date) = :1
                    AND EXTRACT(MONTH FROM payment_date) = :2
                    GROUP BY payment_method
                """, (year, month))
                payment_methods = []
                rows = cursor.fetchall()
                for row in rows:
                    if row:
                        payment_methods.append({
                            'method': row[0],
                            'count': row[1],
                            'total': float(row[2]) if row[2] else 0
                        })
                report['payment_methods'] = payment_methods
                cursor.close()
                conn.close()
                print(f"✓ Payment methods: {len(payment_methods)} methods")
        except Exception as e:
            print(f"✗ Error getting payment methods: {e}")
        
        # Open complaints
        try:
            conn = get_connection()
            if conn:
                cursor = conn.cursor()
                cursor.execute("SELECT COUNT(*) FROM complaint WHERE status = 'OPEN'")
                row = cursor.fetchone()
                report['open_complaints'] = row[0] if row else 0
                cursor.close()
                conn.close()
                print(f"✓ Open complaints: {report['open_complaints']}")
        except Exception as e:
            print(f"✗ Error getting complaints: {e}")
        
        # Top 5 customers by revenue
        try:
            conn = get_connection()
            if conn:
                cursor = conn.cursor()
                cursor.execute("""
                    SELECT cu.customer_id, cu.first_name || ' ' || cu.last_name as name,
                           COUNT(i.invoice_id) as invoice_count, NVL(SUM(i.total_amount), 0) as total_revenue
                    FROM customer cu
                    LEFT JOIN invoice i ON cu.customer_id = i.customer_id 
                        AND EXTRACT(YEAR FROM i.billing_period_start) = :1
                        AND EXTRACT(MONTH FROM i.billing_period_start) = :2
                    GROUP BY cu.customer_id, cu.first_name, cu.last_name
                    ORDER BY total_revenue DESC
                """, (year, month))
                top_customers = []
                rows = cursor.fetchall()
                count = 0
                for row in rows:
                    if row and count < 5:
                        top_customers.append({
                            'customer_id': row[0],
                            'name': row[1],
                            'invoice_count': row[2],
                            'total_revenue': float(row[3]) if row[3] else 0
                        })
                        count += 1
                report['top_customers'] = top_customers
                cursor.close()
                conn.close()
                print(f"✓ Top customers: {len(top_customers)} customers")
        except Exception as e:
            print(f"✗ Error getting top customers: {e}")
        
        # New customers this month
        try:
            conn = get_connection()
            if conn:
                cursor = conn.cursor()
                cursor.execute("""
                    SELECT COUNT(*) FROM customer 
                    WHERE EXTRACT(YEAR FROM registration_date) = :1
                    AND EXTRACT(MONTH FROM registration_date) = :2
                """, (year, month))
                row = cursor.fetchone()
                report['new_customers'] = row[0] if row else 0
                cursor.close()
                conn.close()
                print(f"✓ New customers: {report['new_customers']}")
        except Exception as e:
            print(f"✗ Error getting new customers: {e}")
        
        print("✓ Monthly report generated successfully")
        # Derived metrics
        if report['invoice_count_month'] > 0:
            report['avg_invoice_value_month'] = float(report['total_revenue']) / float(report['invoice_count_month'])
        else:
            report['avg_invoice_value_month'] = 0

        if report['payments_count_month'] > 0:
            report['avg_payment_value_month'] = float(report['total_payments']) / float(report['payments_count_month'])
        else:
            report['avg_payment_value_month'] = 0

        return report
    except Exception as e:
        print(f"✗ Fatal error in get_monthly_report: {e}")
        import traceback
        traceback.print_exc()
        return report  # Return partial report with defaults
